#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Change working directory to the top-most Finder window location

cdf() { # short for `cdfinder`
	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Switch Audio

function headset() {
	switchaudiosource -t input -s "External Headphones"
	switchaudiosource -t output -s "External Headphones"
}

function speakers() {
    switchaudiosource -t input -s "MacBook Pro Microphone"
    switchaudiosource -t output -s "MacBook Pro Speakers"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Toggle bluetooth devices

function trackpad() {
    toggle_bt_device "f4-1b-a1-30-7d-87"
}

function cr4bt() {
    toggle_bt_device "00-11-67-c7-5e-78"
}

function toggle_bt_device() {
    mac_addr=$1

    if [[ $(blueutil --is-connected $mac_addr) = '1' ]]
    then
        echo Disconnecting $mac_addr
        blueutil --unpair $mac_addr
    else
        echo Reconnecting $mac_addr
        blueutil --unpair $mac_addr
        sleep 1
        blueutil --pair $mac_addr
        sleep 1
        blueutil --connect $mac_addr
    fi
}

